[package]
name = "df-derive"
version = "0.1.2"
edition = "2024"
authors = ["Giovanni Ramistella <letter.brigade_7s@icloud.com>"]
description = "Procedural derive macro for efficiently converting Rust structs into Polars DataFrames."
license = "MIT"
repository = "https://github.com/gramistella/df-derive"
homepage = "https://github.com/gramistella/df-derive"
documentation = "https://docs.rs/df-derive"
keywords = ["polars", "dataframe", "proc-macro", "finance"]
categories = ["data-structures", "finance"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote = "1.0.41"
syn = { version = "2.0.108", features = ["derive"] }
proc-macro-crate = "3.4.0"

[dev-dependencies]
trybuild = "1.0.113"
polars = { version = "0.52.0", features = ["timezones", "dtype-decimal"] }
chrono = { version = "0.4.42", features = ["serde"] }
rust_decimal = { version = "1.39.0", features = ["serde"] }
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "01_top_level_vec"
harness = false

[[bench]]
name = "02_empty_nested_vec"
harness = false

[[bench]]
name = "03_nested_option"
harness = false

[[bench]]
name = "04_vec_custom_struct"
harness = false

[[bench]]
name = "05_wide_top_level_options"
harness = false

[[bench]]
name = "06_optional_vec_custom_struct"
harness = false

[[bench]]
name = "07_deep_nesting_vec"
harness = false

[[bench]]
name = "08_complex_wrappers"
harness = false
